### ISSUE TITLE
Please help! ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: 'utf-8' codec can't decode....

### ISSUE THREAD

**Issue by liyi193328** [deeplearningais/CUV#10]
My environment is win10 + python3.4+ theano 0.7. when I import theano from teriminal , I get the error like:
## ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: 'utf-8' codec can't decode......

I set log level as debug, get the folloing info : 
INFO (theano.gof.cmodule): Call to 'g++ -march=native' failed,not setting -march flag
DEBUG (theano.gof.cmodule): Compiling for 64 bit architecture
DEBUG (theano.gof.cmodule): Writing module C++ code to C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64\cutils_ext\mod.cpp
DEBUG (theano.gof.cmodule): Generating shared lib C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64\cutils_ext\cutils_ext.pyd
DEBUG (theano.gof.cmodule): Running cmd: C:\Program Files\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0\mingw64\bin\g++.exe -shared -g -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -ID:\Anaconda3\lib\site-packages\numpy\core\include -ID:\Anaconda3\include -o C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64\cutils_ext\cutils_ext.pyd C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64\cutils_ext\mod.cpp -LD:\Anaconda3\libs -LD:\Anaconda3 -lpython34
DEBUG (theano.gof.cmodule): WORKDIR C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64
DEBUG (theano.gof.cmodule): module_name cutils_ext.cutils_ext
DEBUG (theano.tensor.opt): enabling optimization fusion elemwise in fast_run
DEBUG (theano.sandbox.cuda.nvcc_compiler): Writing module C++ code to C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64\cuda_ndarray\mod.cu
DEBUG (theano.sandbox.cuda.nvcc_compiler): Generating shared lib C:\Users\liyi1\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.4.3-64\cuda_ndarray\cuda_ndarray.pyd
##### ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: 'utf-8' codec can't decode byte 0xd5 in position 5319: invalid continuation byte

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavilable)

my theanorc config is : 
 #!sh
[global]
device = gpu
[nvcc]
compiler_bindir=D:\vs2010\VC\bin
flags  = -LD:\Anaconda3\libs
fastmath = True

**Comment by temporaer** [comment]
Hey, I think you want to ask the folks at the theano project.

**Comment by liyi193328** [comment]
Sorry, It's my fault
