### ISSUE TITLE
stuck at 71% building NVCC when make -j

### ISSUE THREAD

**Issue by xingwangsfu** [deeplearningais/CUV#12]
Hi, 

I followed the installation steps. But I get stuck and hang at 71% building NVCC when make -j.

More details are as follows:
CUDA: 7.0
GPU: TITAN X
Linux: Ubuntu 14.04

I made some changes based on the errors produced by make 
1)  add   thrust/extrema.h into CUV/src/cuv/tensor_ops/tensor_ops.cuh 
2) change compute_13 to compute _20 in CUDA_ARCH
3) sm_11_atomic_functions.h to sm_20_atomic_functions.h in src/cuv/tools/cuPrintf.cu

[ 63%] Building NVCC (Device) object src/cuv/./cuv_generated_inst02.cu.o
[ 65%] Building NVCC (Device) object src/cuv/./cuv_generated_inst00.cu.o
[ 66%] Building NVCC (Device) object src/cuv/./cuv_generated_inst09.cu.o
[ 68%] Building NVCC (Device) object src/cuv/./cuv_generated_inst06.cu.o
[ 70%] Building NVCC (Device) object src/cuv/./cuv_generated_inst03.cu.o
[ 71%] Building NVCC (Device) object src/cuv/./cuv_generated_inst04.cu.o

Can someone tell me how to fix this problem?

Thanks.

**Comment by temporaer** [comment]
It really just takes a long time, be patient. 

-------- Ursprüngliche Nachricht --------
Von: kingstar notifications@github.com
Gesendet: 26. November 2015 01:33:57 MEZ
An: deeplearningais/CUV CUV@noreply.github.com
Betreff: [CUV] stuck at 71% building NVCC when make -j (#12)

Hi, 

I followed the installation steps. But I get stuck and hang at 71% building NVCC when make -j.

More details are as follows:
CUDA: 7.0
GPU: TITAN X
Linux: Ubuntu 14.04

I made some changes based on the errors produced by make 
1)  add  #include <thrust/extrema.h> in CUV/src/cuv/tensor_ops/tensor_ops.cuh 
2) change compute_13 to compute _20 in CUDA_ARCH
3) sm_11_atomic_functions.h to sm_20_atomic_functions.h in src/cuv/tools/cuPrintf.cu

[ 63%] Building NVCC (Device) object src/cuv/./cuv_generated_inst02.cu.o
[ 65%] Building NVCC (Device) object src/cuv/./cuv_generated_inst00.cu.o
[ 66%] Building NVCC (Device) object src/cuv/./cuv_generated_inst09.cu.o
[ 68%] Building NVCC (Device) object src/cuv/./cuv_generated_inst06.cu.o
[ 70%] Building NVCC (Device) object src/cuv/./cuv_generated_inst03.cu.o
[ 71%] Building NVCC (Device) object src/cuv/./cuv_generated_inst04.cu.o

Can someone tell me how to fix this problem?

Thanks.

---

Reply to this email directly or view it on GitHub:
https://github.com/deeplearningais/CUV/issues/12

**Comment by xingwangsfu** [comment]
Thanks. You're right. After a while, it showed [100%] built target cuv_python.
However, when I run ctest, it shows "0% tests passed, 15 tests failed out of 15".

The reason is "Unable to find executable: CUV/build/release/src/tests/lib_rbm, lib_kmeans,...."

Besides, during the make, there are some warnings which may be related to the failure of ctest 
"src/cuv/convolution_ops/convolution_ops.cu(380): warning: statement is unreachable
          detected during instantiation of "void cuv::alex_conv::d_conv2d_dfilt(cuv::tensor<V, M, T> &, const cuv::tensor<V, M, T> &, const cuv::tensor<V, M, T> &, int, unsigned int, unsigned int, unsigned int, float, float) [with V=float, M=cuv::host_memory_space, T=cuv::row_major]" 
(1590): here"

Any suggestions?

**Comment by xingwangsfu** [comment]
Thanks. You're right. After a while, it showed [100%] built target cuv_python.
However, when I run ctest, it shows "0% tests passed, 15 tests failed out of 15".

The reason is "Unable to find executable: CUV/build/release/src/tests/lib_rbm, lib_kmeans,...."

Besides, during the make, there are some warnings which may be related to the failure of ctest 
"src/cuv/convolution_ops/convolution_ops.cu(380): warning: statement is unreachable
          detected during instantiation of "void cuv::alex_conv::d_conv2d_dfilt(cuv::tensor<V, M, T> &, const cuv::tensor<V, M, T> &, const cuv::tensor<V, M, T> &, int, unsigned int, unsigned int, unsigned int, float, float) [with V=float, M=cuv::host_memory_space, T=cuv::row_major]" 
(1590): here"

Any suggestions?

**Comment by temporaer** [comment]
Try running make test instead/before ctest. The warnings are fine. 

-------- Ursprüngliche Nachricht --------
Von: kingstar notifications@github.com
Gesendet: 27. November 2015 02:04:54 MEZ
An: deeplearningais/CUV CUV@noreply.github.com
CC: Hannes Schulz schulz@ais.uni-bonn.de
Betreff: Re: [CUV] stuck at 71% building NVCC when make -j (#12)

Thanks. You're right. After a while, it showed [100%] built target cuv_python.
However, when I run ctest, it shows "0% tests passed, 15 tests failed out of 15".

The reason is "Unable to find executable: CUV/build/release/src/tests/lib_rbm, lib_kmeans,...."

Besides, during the make, there are some warnings which may be related to the failure of ctest 
"src/cuv/convolution_ops/convolution_ops.cu(380): warning: statement is unreachable
          detected during instantiation of "void cuv::alex_conv::d_conv2d_dfilt(cuv::tensor<V, M, T> &, const cuv::tensor<V, M, T> &, const cuv::tensor<V, M, T> &, int, unsigned int, unsigned int, unsigned int, float, float) [with V=float, M=cuv::host_memory_space, T=cuv::row_major]" 
(1590): here"

Any suggestions? 

---
